---
- hosts: all
  vars:
    packages:
      - htop
      - vim
      - git
      - tor
      - zsh
      - clang
      - libevent-devel
      - ncurses-devel
      - bison
    pip_packages:
      - ansible
  tasks:
    - name: Install packages
      sudo: yes
      dnf: name={{ item }} state=present
      with_items: packages
    - name: Enable and start tor
      sudo: yes
      service: name=tor enabled=yes state=started
    - name: Install system pip packages
      sudo: yes
      pip: name={{ item }}
      with_items: pip_packages
    - name: Hush login
      file: path=~/.hushlogin state=touch
