---
- hosts: all
  vars:
    packages:
      - htop
      - vim
      - git
      - tor
  tasks:
    - name: Install packages
      sudo: yes
      dnf: name={{ item }} state=present
      with_items: packages
    - name: Enable and start tor
      sudo: yes
      service: name=tor enabled=yes state=started
