---
- hosts: all
  vars:
    packages:
      - htop
      - neovim
      - python2-neovim
      - python3-neovim
      - git
      - the_silver_searcher
  tasks:
    - name: Install packages
      become: yes
      dnf: name={{ item }} state=present
      with_items: packages
    - name: Install system ansible
      become: yes
      pip: name=ansible
    - name: Install virtualenv
      become: yes
      pip: name=virtualenv
    - name: Install virtualenvwrapper
      become: yes
      pip: name=virtualenvwrapper
    - name: Hush login
      file: path=~/.hushlogin state=touch
    - name: Install postgresql
      become: yes
      dnf: name={{ item }} state=present
      with_items:
        - postgresql-contrib
        - postgresql-server
      register: postgresql
    - name: Configure postgresql
      become: yes
      command: postgresql-setup initdb
      when: postgresql.changed
    - name: Install postgres dev packages
      become: yes
      dnf: name={{ item }} state=present
      with_items:
        - postgresql-devel
        - postgresql-libs
    - name: Ensure postgresql enabled
      become: yes
      service: name=postgresql enabled=yes state=started
