---
- hosts: all
  vars:
    packages:
      - redhat-rpm-config
      - python3-devel
      - openssl-devel
      - fish
      - htop
      - neovim
      - python2-neovim
      - python3-neovim
      - git
      - the_silver_searcher
      - xrdp
      - sway
    ansible_python_interpreter: "/usr/bin/python3"
  tasks:
    - name: Ensure fastestmirror
      become: yes
      lineinfile:
        dest: /etc/dnf/dnf.conf
        regexp: '^fastestmirror'
        line: 'fastestmirror=true'
    - name: Install packages
      become: yes
      dnf:
        name: "{{ item }}"
        state: present
        enablerepo: "http://download.opensuse.org/repositories/shells:fish:release:2/Fedora_24/shells:fish:release:2.repo"
      with_items: "{{ packages }}"
    - name: Set fish as shell
      user: name={{ ansible_user_id }} shell=/usr/bin/fish
    - name: Install system ansible
      become: yes
      pip: name=ansible
    - name: Install virtualenv
      become: yes
      pip: name=virtualenv
    - name: Install virtualfish
      become: yes
      pip: name=virtualfish
    - name: Hush login
      file: path=~/.hushlogin state=touch
    - name: Install postgresql
      become: yes
      dnf: name={{ item }} state=present
      with_items:
        - postgresql-contrib
        - postgresql-server
      register: postgresql
    - name: Configure postgresql
      become: yes
      command: postgresql-setup initdb
      when: postgresql.changed
    - name: Install postgres dev packages
      become: yes
      dnf: name={{ item }} state=present
      with_items:
        - postgresql-devel
        - postgresql-libs
    - name: Ensure postgresql enabled
      become: yes
      service: name=postgresql enabled=yes state=started
    - name: Ensure xrdp enabled
      become: yes
      service: name=xrdp enabled=yes state=started
    - name: Allow xrdp firewall access
      firewalld: port=3389/tcp permanent=true state=enabled immediate=yes
    - name: Configure xrdp to use sway
      copy: src=startwm.sh dest=/etc/xrdp/startwm.sh
